city_color_dict = {
    'blue': ["san_francisco",
    "chicago",
    "montreal",
    "new_york",
    "washington",
    "atlanta",
    "london",
    "madrid",
    "paris",
    "essen",
    "milan",
    "st_petersburg"],

'yellow': ["los_angeles",
    "mexico_city",
    "miami",
    "bogota",
    "lima",
    "santiago",
    "sao_paolo",
    "buenos_aires",
    "lagos",
    "kinshasa",
    "khartoum",
    "johannesburg"],

'black':  ["algiers",
    "istanbul",
    "cairo",
    "moscow",
    "baghdad",
    "riyadh",
    "tehran",
    "karachi",
    "mumbai",
    "delhi",
    "chennai",
    "kolkata"],

'red': ["bangkok",
    "jakarta",
    "beijing",
    "shanghai",
    "hong_kong",
    "ho_chi_minh_city",
    "seoul",
    "taipei",
    "manila",
    "sydney",
    "tokyo",
    "osaka"]

}
