CITY_MAX_DISEASE_CUBES = 3
CITY_MIN_DISEASE_CUBES = 0
HAND_SIZE_LIMIT = 7
NUM_CUBES = 24
NUM_PLAYER_CARDS_DRAW = 2
DISEASE_COLORS = ['black','blue','red','yellow']
START_CITY='atlanta'
GAME_RESULT_ARG_IND = 1
NUM_ACTIONS = 4
PLAYER_HAND_FULL_ERROR = "Can't add, player's hand is full"
NUM_START_CARDS = [None, None, 6, 3, 2] #FIXME 6 to 4
START_CITY_HAS_RESEARCH_STATION = True
MAX_RESEARCH_STATIONS = 6
INITIAL_CITY_INFECTION_AMOUNTS = [3,3,3, 2,2,2, 1,1,1]
INFECTION_RATE = [2,2,3,3,4,4]
NUM_CARDS_FOR_CURE = 5
PLAYER_ACTION_LIST = ['drive_ferry','direct_flight','charter_flight', 'shuttle_flight','build_research_station','treat_disease','discover_cure','give_knowledge','take_knowledge']
GAME_ACTION_LIST = PLAYER_ACTION_LIST + ['discard_card']
GAME_STATUSES = ["player action", "player arg", "draw card", "infect cities"]
MAX_OUTBREAKS = 8
REWARD_LEVEL_SCALE = 100
